M48
; DRILL file {KiCad 8.0.1} date 2024-03-22T19:39:56+0100
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-03-22T19:39:56+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.400
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.380
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.180
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C3.550
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T5C4.300
%
G90
G05
T1
X51.0Y-84.5
X57.2Y-69.5
T2
X64.78Y-44.605
X64.78Y-67.605
T3
X72.98Y-60.345
X72.98Y-83.345
T4
X128.18Y-44.605
X128.18Y-67.605
T5
X35.065Y-72.56
X35.065Y-128.49
X146.935Y-72.56
X146.935Y-128.49
M30
